language: minimal
jobs:
  include:
  - categoryName: "regression"
    env: CATEGORY_TO_TEST=regression
  - categoryName: "regressionTS"
    env: CATEGORY_TO_TEST=regressionTS
  - categoryName: "regressionLTSts"
    env: CATEGORY_TO_TEST=regressionLTSts
  - categoryName: "regressionEXT"
    env: CATEGORY_TO_TEST=regressionEXT
  - categoryName: "multivariate"
    env: CATEGORY_TO_TEST=multivariate
  - categoryName: "multivariate-clustering"
    env: CATEGORY_TO_TEST=multivariate-clustering
  - categoryName: "regression-clustering"
    env: CATEGORY_TO_TEST=regression-clustering
  - categoryName: "mixsim"
    env: CATEGORY_TO_TEST=mixsim
  - categoryName: "utilities"
    env: CATEGORY_TO_TEST=utilities
  - categoryName: "graphics"
    env: CATEGORY_TO_TEST=graphics
dist: xenial
install:
    - travis_wait 360
    - wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
script: matlab -batch "run runAllMyTestsFS.m"       

 