% FSDA
%
% File names, description, category and date last modified
%
%   Name          - Description                                                                                                                                                         - Category- Date last modified
%--------------------------------------------------------------------------------------------------------------------------------------------------------------------
%   add2spm       - Adds objects (personalized clickable multilegends and text labels) to the scatter plot matrix                                                                       - VIS-Mult- 2016 May 09
%   add2yX        - Adds objects to the yXplot                                                                                                                                          - VIS-Reg- 2016 May 09
%   addt          - Produces the t test for an additional expl. variable                                                                                                                - REG-Regression- 2016 May 09
%   basicPower    - Computes the basic power transformation                                                                                                                             - UTISTAT- 2016 May 09
%   bc            - Returns the Binomial coefficient                                                                                                                                    - UTICOMB- 2016 May 09
%   boxplotb      - Computes a bivariate boxplot                                                                                                                                        - VIS-Mult- 2016 May 09
%   brushFAN      - Displays a GUI which enables brushing in the fanplot                                                                                                                - GUI    - 2016 May 11
%   brushRES      - Displays a GUI which enables brushing in resfwdplot                                                                                                                 - GUI    - 2016 May 09
%   brushROB      - Displays a GUI which enables brushing in resindexplot                                                                                                               - GUI    - 2016 May 11
%   cabc          - Closes all open figures except the one in foreground (the current)                                                                                                  - UTIGEN - 2016 May 10
%   cascade       - Is a third party function used in FSDA demos and examples                                                                                                           - UTIGEN - 2016 May 09
%   cdsplot       - Produces the candlestick plot for robust model selection in linear regression                                                                                       - VIS-Reg- 2016 May 09
%   chkinputM     - Makes some input parameters and user options checking in multivariate analysis                                                                                      - UTIGEN - 2016 May 10
%   chkinputR     - Makes some input parameters and user options checking in regression                                                                                                 - UTIGEN - 2016 May 10
%   chkinputRB    - Makes some input parameters and user options checking in Bayes context                                                                                              - UTIGEN - 2016 May 09
%   chkoptions    - Checks whether all supplied options exist                                                                                                                           - UTIGEN - 2016 May 09
%   clickableMultiLegend - Extends the clickableLegend by Ameya Deoras to figures with one legend for several subplots                                                                         - UTIGEN - 2016 May 09
%   combsFS       - Is an iterative algorithm equivalent to the MATLAB combs.m                                                                                                          - UTICOMB- 2016 May 09
%   ComputePars   - Computes parameters needed for computing overlap                                                                                                                    - CLUS-MixSim- 2016 May 09
%   covplot       - Plots the trajectories of the elements of the covariance (correlation) matrix monitored                                                                             - VIS-Mult- 2016 May 09
%   dsxy2figxy    - Transforms points or positions from 'axes data units' to 'normalized figure units'                                                                                  - UTIGEN - 2016 May 09
%   ellipse       - Generates an ellipse given mu (location vector) and Sigma (scatter matrix)                                                                                          - UTISTAT- 2016 May 09
%   estepFS       - Performs e-step for Gaussian mixture distribution                                                                                                                   - CLUS-RobClaMULT- 2016 May 09
%   fanplot       - Plots the fan plot for transformation in linear regression                                                                                                          - VIS-Reg- 2016 May 09
%   findDir       - Finds recursively all directories in root                                                                                                                           - UTIGEN - 2016 May 11
%   findFile      - Finds recursively all files in root                                                                                                                                 - UTIGEN - 2016 May 09
%   FSM           - Gives an automatic outlier detection procedure in mult. analysis                                                                                                    - MULT-Multivariate- 2016 May 09
%   FSMbbm        - Gives the units belonging to subset at step(s) msel of the forward search                                                                                           - MULT-Multivariate- 2016 May 09
%   FSMbonfbound  - Computes Bonferroni bounds for each step of the  search (in mult analysis)                                                                                          - UTISTAT- 2016 May 09
%   FSMbsb        - Gives the units belonging to subset at step(s) msel of the forward search                                                                                           - MULT-Multivariate- 2016 May 09
%   FSMeda        - Performs forward search in multivariate analysis with exploratory data analysis purposes                                                                            - MULT-Multivariate- 2016 May 09
%   FSMenvmmd     - Computes the theoretical envelopes of Minimum MD outside subset during the search                                                                                   - MULT-Multivariate- 2016 May 09
%   FSMfan        - Computes confirmatory lrt of a suggested transformation                                                                                                             - MULT-Transformations- 2016 May 09
%   FSMinvmmd     - Converts values of minimum Mahalanobis distance into confidence levels                                                                                              - MULT-Multivariate- 2016 May 09
%   FSMmmd        - Monitors minMD                                                                                                                                                      - MULT-Multivariate- 2016 May 09
%   FSMmmdeasy    - Is exactly equal to minMD but much less efficient                                                                                                                   - MULT-Multivariate- 2016 May 09
%   FSMmmdrs      - FSRmmdrs performs random start monitoring of minimum Mahalanobis distance                                                                                           - CLUS-RobClaMULT- 2016 May 11
%   FSMtra        - Computes MLE of transformation parameters                                                                                                                           - MULT-Transformations- 2016 May 09
%   FSR           - Gives an automatic outlier detection procedure in linear regression                                                                                                 - REG-Regression- 2016 May 09
%   FSRaddt       - Produces t deletion tests for each expl. variable                                                                                                                   - REG-ModelSelection- 2016 May 09
%   FSRB          - Gives an automatic outlier detection procedure in Bayesian linear regression                                                                                        - REG-Bayes- 2016 May 09
%   FSRBbsb       - Returns the units belonging to the subset in each step of the Bayesian forward search                                                                               - REG-Regression- 2016 May 09
%   FSRBeda       - Enables to monitor several quantities in each step of the Bayesian search                                                                                           - REG-Bayes- 2016 May 09
%   FSRBmdr       - Computes minimum deletion residual and other basic linear regression quantities in each step of the Bayesian search                                                 - REG-Bayes- 2016 May 09
%   FSRbonfbound  - Computes Bonferroni bounds for each step of the search (in linear regression)                                                                                       - UTISTAT- 2016 May 09
%   FSRBr         - Bayesian forward search in linear regression reweighted                                                                                                             - REG-Bayes- 2016 May 09
%   FSRbsb        - Returns the units belonging to the subset in each step of the forward search                                                                                        - REG-Regression- 2016 May 09
%   FSRcp         - Monitors Cp and AIC for all models of interest of size smallp                                                                                                       - REG-ModelSelection- 2016 May 09
%   FSReda        - Enables to monitor several quantities in each step of the forward search                                                                                            - REG-Regression- 2016 May 09
%   FSRenvmdr     - Computes the theoretical envelopes of Minimum Deletion Residual outside subset during the search                                                                    - REG-Regression- 2016 May 09
%   FSRfan        - Monitors the values of the score test statistic for each lambda                                                                                                     - REG-Transformations- 2016 May 09
%   FSRH          - Gives an automatic outlier detection procedure in heteroskedastic linear regression                                                                                 - REG-Hetero- 2016 May 09
%   FSRHbsb       - Returns the units belonging to the subset in each step of the heteroskedastic forward search                                                                        - REG-Hetero- 2016 May 09
%   FSRHeda       - Enables to monitor several quantities in each step of the forward search                                                                                            - REG-Hetero- 2016 May 09
%   FSRHmdr       - Computes minimum deletion residual and other basic linear regression quantities in each step of the heteroskedastic search                                          - REG-Hetero- 2016 May 09
%   FSRinvmdr     - Converts values of minimum deletion residual into confidence levels                                                                                                 - REG-Regression- 2016 May 09
%   FSRmdr        - Computes minimum deletion residual and other basic linear regression quantities in each step of the search                                                          - REG-Regression- 2016 May 09
%   FSRmdrrs      - Performs random start monitoring of minimum deletion residual                                                                                                       - CLUS-RobClaREG- 2016 May 09
%   FSRms         - Performs robust model selection using flexible trimming in linear regression                                                                                        - REG-ModelSelection- 2016 May 09
%   FSRr          - Forward search in linear regression reweighted                                                                                                                      - REG-Regression- 2016 May 09
%   GetOmegaMap   - Calculates the map of misclassificaton between groups                                                                                                               - CLUS-MixSim- 2016 May 09
%   GetOmegaMapv1 - Calculates the map of misclassificaton between groups when v=1                                                                                                      - CLUS-MixSim- 2016 May 09
%   HAbdp         - Finds the constant c associated to the supplied breakdown point                                                                                                     - UTISTAT- 2016 May 09
%   HAc           - Computes breakdown point and efficiency associated with constant c                                                                                                  - UTISTAT- 2016 May 09
%   HAeff         - Finds the tuning constant guarrantees a requested asymptotic efficiency                                                                                             - UTISTAT- 2016 May 09
%   HApsi         - Computes psi function  using Hampel proposal                                                                                                                        - UTISTAT- 2016 May 09
%   HApsider      - Computes derivative of psi function  using Hampel proposal                                                                                                          - UTISTAT- 2016 May 09
%   HApsix        - Computes psi function  using Hampel proposal times x                                                                                                                - UTISTAT- 2016 May 09
%   HArho         - Computes rho function  using Hampel proposal                                                                                                                        - UTISTAT- 2016 May 09
%   HAwei         - Computes weight function psi(u)/u using Hampel proposal                                                                                                             - UTISTAT- 2016 May 09
%   histFS        - Plots a histogram with the elements in each bin grouped according to a vector of labels                                                                             - VIS-Reg- 2016 May 09
%   HUeff         - Finds the constant c which is associated to the requested efficiency for Tukey biweight estimator                                                                   - UTISTAT- 2016 May 11
%   HUpsi         - Computes psi function (derivative of rho function) for Huber                                                                                                        - UTISTAT- 2016 May 11
%   HUpsider      - Computes derivative of psi function (second derivative of rho function) for Tukey's biweight                                                                        - UTISTAT- 2016 May 09
%   HUpsix        - Computes psi function (derivative of rho function) times x for Tukey's biweight                                                                                     - UTISTAT- 2016 May 09
%   HUrho         - Computes (rho) function for Huber                                                                                                                                   - UTISTAT- 2016 May 09
%   HUwei         - Computes weight function psi(u)/u for Huber                                                                                                                         - UTISTAT- 2016 May 09
%   HYPbdp        - Finds constant c which is associated to the requested breakdown                                                                                                     - UTISTAT- 2016 May 09
%   HYPc          - Computes breakdown point and efficiency associated with constant chyperbolic tangent estimator (for a given value of k=sup CVC)                                     - UTISTAT- 2016 May 09
%   HYPck         - Computes values of the scalars A, B, d for hyperbolic tangent estimator                                                                                             - UTISTAT- 2016 May 09
%   HYPeff        - Finds constant c which is associated to the requested efficiency for hyperbolic estimator                                                                           - UTISTAT- 2016 May 09
%   HYPk          - Computes breakdown point and efficiency associated with constant k=sup CVC for hyperbolic tangent estimator (for a given value of c)                                - UTISTAT- 2016 May 09
%   HYPpsi        - Computes psi function for hyperbolic tangent estimator                                                                                                              - UTISTAT- 2016 May 09
%   HYPpsider     - Computes derivative of psi function for hyperbolic tangent estimator                                                                                                - UTISTAT- 2016 May 09
%   HYPpsix       - Computes psi function for hyperbolic tangent estimator times x                                                                                                      - UTISTAT- 2016 May 09
%   HYPrho        - Computes rho function  using hyperboloc tangent estimator                                                                                                           - UTISTAT- 2016 May 09
%   HYPwei        - Computes weight function psi(u)/u for hyperbolic tangent estimator                                                                                                  - UTISTAT- 2016 May 09
%   inversegamcdf - Inversegampdf Inverse-gamma cumulative distribution function                                                                                                        - UTISTAT- 2016 May 09
%   inversegaminv - Inversegampdf Inverse-gamma cumulative distribution function                                                                                                        - UTISTAT- 2016 May 09
%   inversegampdf - Inverse-gamma probability density function                                                                                                                          - UTISTAT- 2016 May 09
%   levfwdplot    - Plots the trajectories of leverage along the search                                                                                                                 - VIS-Reg- 2016 May 09
%   lexunrank     - Gives the the $k$-combination of $n$ elements of position $N$ in the lexicographic order of all combinations                                                        - UTICOMB- 2016 May 09
%   lga           - Performs linear grouping analysis                                                                                                                                   - CLUS-RobClaREG- 2016 May 09
%   logmvnpdfFS   - Produces log of Multivariate normal probability density function (pdf)                                                                                              - UTISTAT- 2016 May 09
%   LXS           - Computes the Least Median of Squares (LMS) or Least Trimmed Squares (LTS) estimators                                                                                - REG-Regression- 2016 May 09
%   mahalFS       - Computes Mahalanobis distances (in squared units) for each row of matrix Y                                                                                          - UTISTAT- 2016 May 09
%   makecontentsfileFS - Extends Matlab function makecontentsfile                                                                                                                            - UTIGEN - 2016 May 11
%   malfwdplot    - Plots the trajectories of scaled Mahalanobis distances along the search                                                                                             - VIS-Mult- 2016 May 09
%   malindexplot  - Plots the Mahalanobis distances versus a selected variable                                                                                                          - VIS-Mult- 2016 May 09
%   mcd           - Computes Minimum Covariance Determinant                                                                                                                             - MULT-Multivariate- 2016 May 09
%   mdrplot       - Plots the trajectory of minimum deletion residual (mdr)                                                                                                             - VIS-Reg- 2016 May 09
%   minscale      - Finds the M estimator of the scale for TB                                                                                                                           - UTISTAT- 2016 May 09
%   MixSim        - Generates k clusters in v dimensions with given overlap                                                                                                             - CLUS-MixSim- 2016 May 09
%   MixSimreg     - Generates k regression hyperplanes in p dimensions with given overlap                                                                                               - CLUS-MixSim- 2016 May 09
%   mmdplot       - Plots the trajectory of minimum mhalanobis distance (mmd)                                                                                                           - VIS-Mult- 2016 May 09
%   MMmult        - Computes MM estimators in multivariate analysis with auxiliary S-scale                                                                                              - MULT-Multivariate- 2016 May 09
%   MMmultcore    - Computes multivariate MM estimators for a selected fixed scale                                                                                                      - MULT-Multivariate- 2016 May 09
%   MMreg         - Computes MM estimator of regression coefficients                                                                                                                    - REG-Regression- 2016 May 09
%   MMregcore     - Computes MM regression estimators for a selected fixed scale                                                                                                        - REG-Regression- 2016 May 09
%   Mscale        - Finds the M estimator of the scale                                                                                                                                  - UTISTAT- 2016 May 09
%   mve           - Computes Minimum volume ellipsoid                                                                                                                                   - MULT-Multivariate- 2016 May 09
%   nchoosekFS    - Returns the Binomial coefficient or matrix containing all combinations                                                                                              - UTICOMB- 2016 May 09
%   ncx2mixtcdf   - Cumulative distribution function (cdf) of a linear combination of non-central chi-square (+ sigma * N(0,1))                                                         - UTISTAT- 2016 May 09
%   normBoxCox    - Computes (normalized) Box-Cox transformation                                                                                                                        - UTISTAT- 2016 May 09
%   normYJ        - Computes (normalized) Yeo-Johnson transformation                                                                                                                    - UTISTAT- 2016 May 09
%   olsline       - Adds least-squares fit line(s) to scatter plot(s)                                                                                                                   - VIS-Reg- 2016 May 09
%   OPTbdp        - Finds the constant c associated to the supplied breakdown point                                                                                                     - UTISTAT- 2016 May 09
%   OPTc          - Computes breakdown point and efficiency associated with constant c for Optimal rho function                                                                         - UTISTAT- 2016 May 09
%   OPTeff        - Finds the constant c which is associated to the requested efficiency                                                                                                - UTISTAT- 2016 May 09
%   OPTpsi        - Computes psi function (derivative of rho function) for optimal weight function                                                                                      - UTISTAT- 2016 May 09
%   OPTpsider     - Computes derivative of psi function (second derivative of rho function) for optimal weight function                                                                 - UTISTAT- 2016 May 09
%   OPTpsix       - Computes psi function (derivative of rho function) times x                                                                                                          - UTISTAT- 2016 May 09
%   OPTrho        - Computes rho function for optimal weight function                                                                                                                   - UTISTAT- 2016 May 09
%   OPTwei        - Computes weight function psi(u)/u for optimal weight function                                                                                                       - UTISTAT- 2016 May 09
%   overlap       - Computes the exact overlap given the parameters of the mixture                                                                                                      - CLUS-MixSim- 2016 May 09
%   PoolClose     - Closes the pool of MATLAB instances opened with PoolPrepare to execute code in parallel                                                                             - UTIGEN - 2016 May 09
%   PoolPrepare   - Prepares a pool of MATLAB instances for executing code in parallel                                                                                                  - UTIGEN - 2016 May 09
%   position      - Controls the position of the open figures                                                                                                                           - UTIGEN - 2016 May 09
%   Powertra      - Computes power transformation (Box-Cox or  Yeo-Johnson)                                                                                                             - UTISTAT- 2016 May 09
%   predci        - Preci computes prediction intervals in the linear regression model                                                                                                  - REG-Regression- 2016 May 09
%   publishFS     - Enables to create automatic HELP FILES from structured .m function files                                                                                            - UTIGEN - 2016 May 11
%   Qn            - Robust estimator of scale (first quartile of interpoint distances $|x_i-x_j|$)                                                                                      - UTISTAT- 2016 May 09
%   quickselectFS - Finds the k-th order statistic                                                                                                                                      - UTIGEN - 2016 May 09
%   RandIndexFS   - Calculates Rand type Indices to compare two partitions                                                                                                              - UTISTAT- 2016 May 09
%   randsampleFS  - Generates a random sample of k elements from the integers 1 to n (k<=n)                                                                                             - UTICOMB- 2016 May 09
%   regressB      - Computes Bayesian estimates of regression parameters                                                                                                                - REG-Bayes- 2016 May 09
%   regressH      - Fits a multiple linear regression model with heteroskedasticity                                                                                                     - REG-Hetero- 2016 May 09
%   regressHart   - Fits a multiple linear regression model using art heteroskedasticity                                                                                                - REG-Hetero- 2016 May 09
%   regressHart_grid - Grid search to find minimum for ART model                                                                                                                           - REG-Hetero- 2016 May 09
%   regressHhar   - RegressH fits a multiple linear regression model with Harvey heteroskedasticity                                                                                     - REG-Hetero- 2016 May 09
%   regressHhar_grid - Grid search to find minimum for ART model                                                                                                                           - REG-Hetero- 2016 May 09
%   rescale       - Rescales numeric array to have specified minimum (a)  and maximum (b)                                                                                               - UTIGEN - 2016 May 09
%   resfwdplot    - Plots the trajectories of the scaled (squared) residuals monitored                                                                                                  - VIS-Reg- 2016 May 09
%   resindexplot  - Plots the residuals from a regression analysis versus index number or any other variable                                                                            - VIS-Reg- 2016 May 09
%   restreigen    - Computes eigenvalues restriction (without Dykstra algorithm)                                                                                                        - CLUS-RobClaMULT- 2016 May 09
%   rlga          - Performs robust linear grouping analysis                                                                                                                            - CLUS-RobClaREG- 2016 May 09
%   RobCov        - Computes covariance matrix of robust regression coefficients                                                                                                        - REG-Regression- 2016 May 09
%   RobRegrSize   - Provides proper threshold for robust estimators to obtain an empirical size equal to 1 per cent nominal size                                                        - REG-Regression- 2016 May 09
%   Score         - Computes the score test for transformation                                                                                                                          - REG-Transformations- 2016 May 09
%   SDest         - Computes Stahel-Donoho robust estimator of dispersion/location                                                                                                      - MULT-Multivariate- 2016 May 09
%   selectdataFS  - Enables to select data points using the mouse, on scatter plot matrices or trajectories in the forward plots                                                        - UTIGEN - 2016 May 09
%   shuffling     - Does a random permutation of the elements of input vector                                                                                                           - UTICOMB- 2016 May 09
%   simdataset    - Simulates and/or contaminates a dataset given the parameters of finite mixture model with Gaussian components%                                                      - CLUS-MixSim- 2016 May 09
%   simdatasetreg - Simulates regression dataset given the parameters of a mixture regression model                                                                                     - CLUS-MixSim- 2016 May 09
%   Smult         - Computes S estimators in multivariate analysis                                                                                                                      - MULT-Multivariate- 2016 May 09
%   Sn            - Robust estimator of scale (robust version of Gini's average difference)                                                                                             - UTISTAT- 2016 May 09
%   spmplot       - Produces an interactive scatterplot matrix with boxplots or histograms on the main diagonal                                                                         - VIS-Mult- 2016 May 09
%   Sreg          - Computes S estimators in linear regression                                                                                                                          - REG-Regression- 2016 May 09
%   subsets       - Creates a matrix of indexes where rows are distinct p-subsets extracted from a set of n elements                                                                    - UTICOMB- 2016 May 09
%   tabulateFS    - Create frequency table of unique values of x, excluding possible 0 counts                                                                                           - UTISTAT- 2016 May 09
%   Taureg        - Computes Tau estimators in linear regression                                                                                                                        - REG-Regression- 2016 May 09
%   TBbdp         - Finds the constant c associated to the supplied breakdown point for Tukey's biweight                                                                                - UTISTAT- 2016 May 09
%   TBc           - Computes breakdown point and efficiency associated with constant c for Tukey's biweight                                                                             - UTISTAT- 2016 May 09
%   TBeff         - Finds the constant c which is associated to the requested efficiency for Tukey biweight estimator                                                                   - UTISTAT- 2016 May 09
%   TBpsi         - Computes psi function (derivative of rho function) for Tukey's biweight                                                                                             - UTISTAT- 2016 May 09
%   TBpsider      - Computes derivative of psi function (second derivative of rho function) for Tukey's biweight                                                                        - UTISTAT- 2016 May 09
%   TBpsix        - Computes psi function (derivative of rho function) times x for Tukey's biweight                                                                                     - UTISTAT- 2016 May 09
%   TBrho         - Computes (rho) function for Tukey biweight                                                                                                                          - UTISTAT- 2016 May 09
%   TBwei         - Computes weight function psi(u)/u for Tukey biweight                                                                                                                - UTISTAT- 2016 May 09
%   tclust        - Computes trimmed clustering with restricitons on the eigenvalues                                                                                                    - CLUS-RobClaMULT- 2016 May 09
%   tclustIC      - Computes tclust for different number of groups k and restriction factors c                                                                                          - CLUS-RobClaMULT- 2016 May 09
%   tclustICplot  - Plots information criterion as a function of c and k                                                                                                                - VIS-Mult- 2016 May 09
%   tclustICsol   - Extracts a set of best relevant solutions                                                                                                                           - CLUS-RobClaMULT- 2016 May 09
%   tclustreg     - Performs robust linear grouping analysis                                                                                                                            - CLUS-RobClaREG- 2016 May 09
%   tkmeans       - Computes trimmed k-means                                                                                                                                            - CLUS-RobClaMULT- 2016 May 09
%   triu2vec      - Extracts in a vector the linear indexes or the elements on and above the k-th diagonal of a square matrix                                                           - UTIGEN - 2016 May 09
%   unibiv        - Has the purpose of detecting univariate and bivariate outliers                                                                                                      - MULT-Multivariate- 2016 May 09
%   upperfracpos  - Positions two figures on the upper part of the screen                                                                                                               - UTIGEN - 2016 May 09
%   winsor        - Returns a copy of X in which all entries smaller than the p(1) quantile have been replaced by this value and likewise for all entries larger than the p(2) quantile - UTISTAT- 2016 May 11
%   yXplot        - Produces an interactive scatterplot of y against each variable of X in the input dataset                                                                            - VIS-Reg- 2016 May 09
%   zscoreFS      - Computes (robust) standardized z scores                                                                                                                             - UTIGEN - 2016 May 09
