% add appropriate path
FSroot= fileparts(which('docsearchFS.m'));

f=filesep;

addp=[FSroot ';' ...
    FSroot f 'multivariate;' ...
    FSroot f 'regression;' ...
    FSroot f 'clustering;' ...
    FSroot f 'graphics;' ...
    FSroot f 'datasets' f 'regression;' ...
    FSroot f 'datasets' f 'multivariate;' ...
    FSroot f 'datasets' f 'multivariate_regression;' ...
    FSroot f 'datasets' f 'clustering;' ...
    FSroot f 'combinatorial;' ...
    FSroot f 'utilities;' ...
    FSroot f 'utilities_stat;' ...
    FSroot f 'utilities_help;' ...
    FSroot f 'examples;'...
    FSroot f 'FSDAdemos' ];

path(addp,path);
% run addFSDA2path.m
% LXS with default input and output.
% Compute LMS estimator without reweighting, add intercept to matrix X
% and do not produce plots.
n=200;
p=3;
rng(123456);
X=randn(n,p);
y=randn(n,1);
y(1:5)=y(1:5)+6;
[out]=LXS(y,X);
