---
name: "reusable-build-docker-container"

on:
  workflow_call:
    inputs:
      matlab-release:
        required: false
        type: string
        default: latest
      fsda-release:
        required: true
        type: string
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: josmartin/fsda

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: "./docker"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.fsda-release }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            FSDA_RELEASE=${{ inputs.fsda-release }}
            MATLAB_DOCKER_TAG=${{ inputs.matlab-release }}    