headJS="<head>";
headJS=headJS +	"<meta charset='utf-8'>";
headJS=headJS +	"<meta content='width=device-width, initial-scale=1.0' name='viewport'>";
headJS=headJS +	"<meta content='IE=edge' http-equiv='X-UA-Compatible'>";
headJS=headJS +	"<link href='docstyle.css' rel='stylesheet' type='text/css'>";
headJS=headJS +	"<link href='includesFS/bootstrap.min.css' rel='stylesheet' type='text/css'>";
headJS=headJS +	"<meta content='text/javascript' http-equiv='Content-Script-Type'>";
headJS=headJS +	"<meta content='cat' itemprop='pagetype' name='toctype'>";
headJS=headJS +	"<meta content='cat' itemprop='infotype' name='infotype' />";
headJS=headJS +	"<meta content='Flexible Statistics and Data Analysis Toolbox  provides functions and apps to describe, analyze, and model data using robust statistics' itemprop='description' name='description' />";
headJS=headJS +	"<script src='includesFS/jquery-latest.js' type='text/javascript'></script>";
headJS=headJS +	"<link href='includesFS/site6.css?201601120052' rel='stylesheet' type='text/css'>";
headJS=headJS +	"<link href='includesFS/site6_lg.css?201601120052' media='screen and (min-width: 1200px)' rel='stylesheet'>";
headJS=headJS +	"<link href='includesFS/site6_md.css?201601120052' media='screen and (min-width: 992px) and (max-width: 1199px)' rel='stylesheet'>";
headJS=headJS +	"<link href='includesFS/site6_sm+xs.css?201601120052' media='screen and (max-width: 991px)' rel='stylesheet'>";
headJS=headJS +	"<link href='includesFS/site6_sm.css?201601120052' media='screen and (min-width: 768px) and (max-width: 991px)' rel='stylesheet'>";
headJS=headJS +	"<link href='includesFS/site6_xs.css?201601120052' media='screen and (max-width: 767px)' rel='stylesheet'>";
headJS=headJS +	"<link href='includesFS/site6_offcanvas.css?201601120052' rel='stylesheet' type='text/css'>";
headJS=headJS +	"<script src='includesFS/l10n.js'></script>";
headJS=headJS +	"<script src='includesFS/SHAREDdocscripts.js'></script>";
headJS=headJS +	"<script src='includesFS/PRODUCTdocscripts.js'></script>";
headJS=headJS +	"<script src='includesFS/mw.imageanimation.js'></script>";
headJS=headJS +	"<script src='includesFS/jquery.highlight.js'></script>";
headJS=headJS +	"<script src='includesFS/underscore-min.js'></script>";

headJS=headJS + "<script xmlns='http://www.w3.org/1999/xhtml' src='../includes/shared/scripts/F1help.js'></script>";
headJS=headJS + "<script xmlns='http://www.w3.org/1999/xhtml' src='../includes/product/scripts/suggest.js'></script>";
headJS=headJS + "<script xmlns='http://www.w3.org/1999/xhtml' src='../includes/shared/scripts/helpservices.js'></script>";

headJS=headJS +	"<script src='includesFS/bootstrap.min.js' type='text/javascript'></script>";
headJS=headJS +	"<script src='includesFS/global.js'></script>";
headJS=headJS +	"<script src='includesFS/bottom.js' type='text/javascript'></script>";
headJS=headJS +	"<script src='includesFS/lbar.js' type='text/javascript'></script>";
headJS=headJS +	"<script src='includesFS/lbarSimple.js' type='text/javascript'></script>";
headJS=headJS +	"<script src='includesFS/engine.js' type='text/javascript'></script>";
headJS=headJS +	"<script src='includesFS/divsbefore.js' type='text/javascript'></script>";
headJS=headJS +	"<script src='includesFS/divsafter.js' type='text/javascript'></script>";
headJS=headJS +	"<link href='includesFS/doc_center.css' rel='stylesheet' type='text/css'>";
headJS=headJS +	"<link href='includesFS/doc_center_installed.css' rel='stylesheet' type='text/css'>";
headJS=headJS +	"<link href='includesFS/doc_center_print.css' media='print' rel='stylesheet' type='text/css'>";
headJS=headJS +	"<script type='text/x-mathjax-config'>";
headJS=headJS +	"MathJax.Hub.Config({";
headJS=headJS +	"extensions: ['tex2jax.js'],";
headJS=headJS +	"jax: ['input/TeX','output/HTML-CSS'],";
headJS=headJS +	"menuSettings: {zoom: 'Double-Click', zscale: '300'},";
headJS=headJS +	"tex2jax: {inlineMath: [['$','$'],['\\((','\\))']]},";
headJS=headJS +	"MathMenu: {showRenderer: false},";
headJS=headJS +	"'HTML-CSS': {";
headJS=headJS +	"availableFonts: ['TeX'],";
headJS=headJS +	"preferredFont: 'TeX',";
headJS=headJS +	"imageFont: null";
headJS=headJS +	"}";
headJS=headJS +	"});";
headJS=headJS +	"</script>";
headJS=headJS +	"<script type='text/javascript' src='includesFS/Mathjax/MathJax.js'></script>";
headJS=headJS +	"</head>";

