fcate="<ul class='nav_scrollspy nav' xmlns:atict='http://www.arbortext.com/namespace/atict'>";
fcate=fcate + "<li class='nav_scrollspy_function'><a href='#responsive_offcanvas'>Flexible Statistics and Data Analysis Toolbox</a></li>";
fcate=fcate + "		<li id='SSPY810-article' class='nav_scrollspy_title'>On this page</li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#A'>A</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#B'>B</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#C'>C</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#D'>D</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#E'>E</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#F'>F</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#G'>G</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#H'>H</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#I'>I</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#J'>J</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#K'>K</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#L'>L</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#M'>M</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#N'>N</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#O'>O</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#P'>P</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#Q'>Q</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#R'>R</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#S'>S</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#T'>T</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#U'>U</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#V'>V</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#X'>X</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#Y'>Y</a></li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#Z'>Z</a></li>";
fcate=fcate + "	</ul>";
