function CreateFSDAtoolboxInGithubAction 
%% File which automatically creates toolbox file FSDA.mltbx for fileexchange


%% Beginning of code

% specify the version number, please use the format 'major.minor.revision'
newVersion = getenv('GITHUB_RELEASE_TAG');

if isempty(newVersion)
    disp('Missing a GITHUB_RELEASE_TAG to build the toolbox with')
    error('FSDA:CreateFSDAtoolboxInGithubAction:NoTag','No Tag to define version')
end

% Specify folder where to create the toolbox project
thisMfile = mfilename('fullpath');
thisPath = fileparts(thisMfile);
FSDAProjFolder = fileparts(fileparts(thisPath));


%% Preliminary operations

% Navigate into FSDAProjFolder
try
    cd(FSDAProjFolder)
catch
    disp(['Supplied path "' FSDAProjFolder '" does not exist'])
    error('FSDA:CreatetoolboxProjectFile:WrgPath','Wrong input path')
end

% Get filesep
fsep=filesep;

% Check if FSDA.mltbx exists
% If the answer is yes delete it in order to start from scratch
if isfile('FSDA.mltbx') == true
    delete('FSDA.mltbx')
end

%% NO LONGER NEEDED - REMOVE UNNECESSARY FOLDERS inside project folder
FSroot='FSDA';


%% REMOVE UNNECESSARY FILES

% All png files  inside helpfiles\FSDA\images
% delete([FSroot fsep 'helpfiles' fsep 'FSDA' fsep 'images' fsep '*.png'])

% delete([FSroot fsep 'package.json'])

%% Publish contents file in the root inside subfolder html
% This instruction is necessary in order to display subfolder examples in
% Mathworks web site
oldFolder=pwd;
cd(FSroot)   
publish('Contents.m');
cd(oldFolder)


%% Create searchable database

% save current path
oldpath = path;
path2add=[FSDAProjFolder fsep 'FSDA'];
addpath(path2add);

FileName=[FSroot filesep 'addFSDA2path'];
FullPath=which(FileName);
% Navigate to the main folder of FSDA
FSDAroot = string(fileparts(FullPath));
% FSDApointers = full path for folder which creates pointer files
FSDApointers = FSDAroot + fsep + 'helpfiles' + fsep + 'pointersHTML';

% Starting in R2022a, the builddocsearchdb function creates the subfolder
% helpsearch-v4 to contain the search database files. Previously,
% builddocsearchdb created a subfolder named helpsearch-v3.
% To ensure the documentation for FSDA toolbox is searchable in any version
% we have to run buildocsearchdb also on R2021b

% TODO !!!!

builddocsearchdb(FSDApointers);

% restore previous path
path(oldpath);

%% Create toolbox project file

% uuid =unique identifier name, generated by the following code:
%
% uuid = java.util.UUID.randomUUID
%
% uuid identified of FSDA
uuid = '20669fbc-61ca-4050-bc87-575422f4c0b8';
% Note that when matlab.addons.toolbox.ToolboxOptions the files attached to
% the project are automatically added inside 
% options.Toolboxfiles 
options = matlab.addons.toolbox.ToolboxOptions(FSDAroot, uuid);

options = removeFoldersFromToolboxPackage(options, [ ...
    "_automation_tools"
    "_development"
    "_TODO"
    "helpfiles" + fsep + "XML"
    ".git"
    ".github"
    ".circleci"
    "Univ"
    "docker"
    "bin"
    ".buildtool"
    ]);

options = removeFilesFromToolboxPackage(options, [...
    "examples" + fsep + "examples_categorical.mlx"
    "examples" + fsep + "examples_multivariate.mlx"
    "examples" + fsep + "examples_regression.mlx"
    "examples" + fsep + "examples_MixSim.mlx"
    "utilities_help" + fsep + "FlowChart.pptx"
    "eupllicense.pdf"
    "Copyright notice.pdf"
    "installationNotes.docx"
    "installationNotes.pdf"
    "buildfile.m"
    "FSDA.prj"
    "readme.md"
    "404.md"
    "CODE_OF_CONDUCT.md"
    "CONTRIBUTING.md"
    "helpfiles" + fsep + "FSDA" + fsep + "images" + fsep + "githubimgexamples.jpg"
    "helpfiles" + fsep + "FSDA" + fsep + "images" + fsep + "githubimgindex.jpg"
    "helpfiles" + fsep + "FSDA" + fsep + "images" + fsep + "githubimgtutorials.jpg"    
    ]);


% add FSDA paths
pathsToAdd = [ ...
    ""
    "multivariate"
    "regression"
    "clustering"
    "graphics"
    "datasets" + fsep + "regression"
    "datasets" + fsep + "multivariate"
    "datasets" + fsep + "multivariate_regression"
    "datasets" + fsep + "clustering"
    "combinatorial"
    "utilities"
    "utilities_stat"
    "utilities_help"
    "examples"
    "FSDAdemos"    
    ];

options.ToolboxMatlabPath = FSDAroot + fsep + pathsToAdd;

% add toolbox name
options.ToolboxName = "FSDA";
% add toolbox version
options.ToolboxVersion=newVersion;

% Detailed description of the toolbox.
options.Description="Flexible Statistics and Data Analysis (FSDA) extends MATLAB for " + ...
    "a robust analysis of data sets affected by different sources of heterogeneity. " + ...
    "It is open source software licensed under the European Union Public Licence (EUPL). " + ...
    "FSDA is a joint project by the University of Parma and the Joint Research Centre " + ...
    "of the European Commission."; 

% add summary description of the toolbox
options.Summary="Flexible Statistics Data Analysis Toolbox";

% add toolbox author.
options.AuthorName= "Marco Riani";

% add email address address
options.AuthorEmail = "FSDA@unipr.it";

% added company
options.AuthorCompany = "University of Parma (UNIPR) and Joint Research Centre of the " + ...
    "European Commission(JRC).";
 
% add architecture support (option name changed in the release)
options.SupportedPlatforms.Win64 = true;
options.SupportedPlatforms.Maci64 = true;
options.SupportedPlatforms.Glnxa64 = true;
options.SupportedPlatforms.MatlabOnline = true;

% version compatibility
options.MinimumMatlabRelease = 'R2018a';
options.MaximumMatlabRelease = '';

% add big logo
options.ToolboxImageFile= FSDAroot + fsep + "logoblue.jpg";

% add getting startup file
options.ToolboxGettingStartedGuide = FSDAroot + fsep + 'doc' + fsep + 'GettingStarted.mlx';

% add gallery files
options.AppGalleryFiles=[];
% options.OutputFile='testFSDA';
mkdir(FSDAroot, 'bin')

options.OutputFile = FSDAroot + fsep + "bin" + fsep + "FSDA";

disp(options)

disp('Package toolbox and create file FSDA.mltbx')
matlab.addons.toolbox.packageToolbox(options);


end

function options = removeFoldersFromToolboxPackage(options, foldersToRemove)
root = options.ToolboxFolder;
foldersToRemove = root + filesep + foldersToRemove + filesep;
itemsToRemove = startsWith(options.ToolboxFiles, foldersToRemove);
options.ToolboxFiles(itemsToRemove) = [];
end

function options = removeFilesFromToolboxPackage(options, filesToRemove)
root = options.ToolboxFolder;
filesToRemove = root + filesep + filesToRemove;
itemsToRemove = matches(options.ToolboxFiles, filesToRemove);
options.ToolboxFiles(itemsToRemove) = [];
end