barra="	<table border='0' cellpadding='0' cellspacing='0' class='nav' summary='Navigation aid' width='100%'>";
barra = barra +	"<tr><td width='3%'><div align='center'><img height='6' src='images_help/bullet_orange.gif' width='6'></div>";
barra = barra +	"</td> <td width='25%'> <p><a href='function-cate.html'>By Category</a></p> </td>";
barra = barra +	"<td width='35%'>Functions</td>";
barra = barra +	"<td width='10%'><p><a href='function-alpha.html'>Alphabetical List</a>&nbsp</p></td>";
barra = barra +	"<td width='3%'><img height='6' src='images_help/bullet_orange.gif' width='6'>";
barra = barra +	"</td> </tr> </table> <br>";
barra = barra +	"<p class='copy' style='font-size: small'><tt class='minicdot'>•</tt> <a href='developers.html'>The developers of the toolbox</a>";
barra = barra +	"<tt class='minicdot'>•</tt> <a href='group.html'>The forward search group</a> <tt class='minicdot'>•</tt> <a href='license.txt'>Terms of Use</a>";
barra = barra + "<tt class='minicdot'>•</tt> <a href='acknowledgments.html'>Acknowledgments</a></p>";
barra = barra + "<hr><p>&nbsp;</p><p>&nbsp;</p>";