barra="	<table border='0' cellpadding='0' cellspacing='0' class='nav' width='100%'>";
barra = barra +	"		<tr valign='top'>";
barra = barra +	"			<td align='left' width='20'><a href='%2520'>";
barra = barra +	"			<img align='bottom' alt='' border='0' src='images_help/b_prev.gif'></a>";
barra = barra +	"			</td>";
barra = barra +	"			<td align='left'>left</td>";
barra = barra +	"			<td>&nbsp;</td>";
barra = barra +	"			<td align='right'>right</td>";
barra = barra +	"			<td align='right' width='20'><a href='%2520'>";
barra = barra +	"			<img align='bottom' alt='score' border='0' src='images_help/b_next.gif'></a></td>";
barra = barra +	"		</tr>";
barra = barra +	"	</table>";
barra = barra +	"<hr><table border='0' cellpadding='0' cellspacing='0' class='nav' summary='Navigation aid' width='100%'>";
barra = barra +	"<tr><td width='15'><div align='center'><img height='6' src='images_help/bullet_orange.gif' width='6'></div>";
barra = barra +	"</td> <td> <p><a href='function-cate.html'>By Category</a></p> </td>";
barra = barra +	"<td class='style1'><font size='4' align='center'>Functions</font></td>";
barra = barra +	"<td align='right'><p><a href='function-alpha.html'>Alphabetical List</a>&nbsp</p></td>";
barra = barra +	"<td width='15' ><img height='6' src='images_help/bullet_orange.gif' width='6'>";
barra = barra +	"</td> </tr> </table> <br>";
barra = barra +	"<p class='copy' style='font-size: small'><tt class='minicdot'>•</tt> <a href='developers.html'>The developers of the toolbox</a>";
barra = barra +	"<tt class='minicdot'>•</tt> <a href='group.html'>The forward search group</a> <tt class='minicdot'>•</tt> <a href='license.txt'>Terms of Use</a>";
barra = barra + "<tt class='minicdot'>•</tt> <a href='acknowledgments.html'>Acknowledgments</a></p>";
barra = barra + "<hr><p>&nbsp;</p><p>&nbsp;</p>";