headJS=	"    <title>Flexible Statistics and Data Analysis Toolbox ";
headJS=headJS +	"        Functions - - By Category</title>";
headJS=headJS +	"    <meta content='refpage' name='chunktype'>";
headJS=headJS +	"    <meta content='function:function-cate' itemprop='refentity' name='refentity'>";
headJS=headJS +	"    <meta content='text/javascript' http-equiv='Content-Script-Type'>";
headJS=headJS +	"    <meta content='fcn' itemprop='pagetype' name='toctype'>";
headJS=headJS +	"    <meta content='ref/function' itemprop='infotype' name='infotype' />";
headJS=headJS +	"    <meta content='Check if file exists and puts answer in a cached persistent variable.' itemprop='description' name='description' />";
headJS=headJS +	"    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />";
headJS=headJS +	"    <meta content='IE=EmulateIE7' http-equiv='X-UA-Compatible' />";
headJS=headJS +	"<script type='text/x-mathjax-config'>";
headJS=headJS +	"MathJax.Hub.Config({";
headJS=headJS +	"extensions: ['tex2jax.js'],";
headJS=headJS +	"jax: ['input/TeX','output/HTML-CSS'],";
headJS=headJS +	"menuSettings: {zoom: 'Double-Click', zscale: '300'},";
headJS=headJS +	"tex2jax: {inlineMath: [['$','$'],['\\((','\\))']]},";
headJS=headJS +	"MathMenu: {showRenderer: false},";
headJS=headJS +	"'HTML-CSS': {";
headJS=headJS +	"availableFonts: ['TeX'],";
headJS=headJS +	"preferredFont: 'TeX',";
headJS=headJS +	"imageFont: null";
headJS=headJS +	"}";
headJS=headJS +	"});";
headJS=headJS +	"</script>";
headJS=headJS +	"    <script src='includesFS/Mathjax/MathJax.js' type='text/javascript'></script>";
headJS=headJS +	"<script>";
headJS=headJS +	"(function() {";
headJS=headJS +	"var cx = '007874165161426536790:d2xjm5ikfvg';";
headJS=headJS +	"var gcse = document.createElement('script');"; 
headJS=headJS +	"gcse.type = 'text/javascript';"; 
headJS=headJS +	"gcse.async = true;";
headJS=headJS +	"gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;"; 
headJS=headJS +	"var s = document.getElementsByTagName('script')[0];"; 
headJS=headJS +	"s.parentNode.insertBefore(gcse, s);";
headJS=headJS +	"})();";
headJS=headJS +	"</script>";
headJS=headJS +	"    <script src='includesFS/matlab-highlighter.min.js'></script>";
headJS=headJS +	"    <link href='includesFS/matlab-highlighter.css' rel='stylesheet' type='text/css'>";
headJS=headJS +	"    <script src='includesFS/jquery-latest.js' type='text/javascript'></script>";
headJS=headJS +	"    <link href='../includes/product/css/bootstrap.min.css' rel='stylesheet' type='text/css'></link>";
headJS=headJS +	"    <link href='../includes/product/css/site6.css' rel='stylesheet' type='text/css'></link>";
headJS=headJS +	"    <link href='../includes/product/css/site6_lg.css' media='screen and (min-width: 1200px)' rel='stylesheet'></link>";
headJS=headJS +	"    <link href='../includes/product/css/site6_md.css' media='screen and (min-width: 992px) and (max-width: 1199px)' rel='stylesheet'></link>";
headJS=headJS +	"    <link href='../includes/product/css/site6_sm+xs.css' media='screen and (max-width: 991px)' rel='stylesheet'></link>";
headJS=headJS +	"    <link href='../includes/product/css/site6_sm.css' media='screen and (min-width: 768px) and (max-width: 991px)' rel='stylesheet'></link>";
headJS=headJS +	"    <link href='../includes/product/css/site6_xs.css' media='screen and (max-width: 767px)' rel='stylesheet'></link>";
headJS=headJS +	"    <link href='../includes/product/css/site6_offcanvas.css' rel='stylesheet' type='text/css'></link>";
headJS=headJS +	"    <script src='../includes/shared/scripts/l10n.js' type='text/javascript'></script>";
headJS=headJS +	"    <script src='../includes/product/scripts/docscripts.js'></script>";
headJS=headJS +	"    <script src='../includes/shared/scripts/docscripts_rn.js'></script>";
headJS=headJS +	"    <script src='../includes/shared/scripts/mw.imageanimation.js' type='text/javascript'></script>";
headJS=headJS +	"    <script src='../includes/shared/scripts/jquery.highlight.js'></script>";
headJS=headJS +	"    <script src='../includes/product/scripts/bootstrap.min.js' type='text/javascript'></script>";
headJS=headJS +	"    <script src='../includes/product/scripts/global.js'></script>";
headJS=headJS +	"<script src='includesFS/bottom.js' type='text/javascript'></script>";
headJS=headJS +	"<script src='includesFS/lbar.js' type='text/javascript'></script>";
headJS=headJS +	"<script src='includesFS/lbarSimple.js' type='text/javascript'></script>";
headJS=headJS +	"    <!-- always be sure that engineweb.js is included on web pages and NOT engine.js that is for the local help -->";
headJS=headJS +	"<script src='includesFS/engineweb.js' type='text/javascript'></script>";
headJS=headJS +	"<script src='includesFS/divsbefore.js' type='text/javascript'></script>";
headJS=headJS +	"<script src='includesFS/divsafter.js' type='text/javascript'></script>";
headJS=headJS +	"    <script src='../includes/product/scripts/underscore-min.js'></script>";
headJS=headJS +	"    <script src='../includes/shared/scripts/f1help.js' type='text/javascript'></script>";
headJS=headJS +	"    <script src='../includes/product/scripts/suggest.js' type='text/javascript'></script>";
headJS=headJS +	"    <script src='../includes/shared/scripts/helpservices.js' type='text/javascript'></script>";
headJS=headJS +	"    <script src='../includes/product/scripts/jquery/jquery.mobile.custom.min.js'></script>";
headJS=headJS +	"    <!-- the following line should be kept this way only -->";
headJS=headJS +	"    <link href='includesFS/doc_center.css' rel='stylesheet' type='text/css'></link>";
headJS=headJS +	"    <link href='../includes/product/css/doc_center_installed.css' rel='stylesheet' type='text/css'>";
headJS=headJS +	"    <link href='../includes/product/css/doc_center_print.css' media='print' rel='stylesheet' type='text/css'>";
