headJSm="<head>";
headJSm=headJSm +	"<meta charset='utf-8'>";
headJSm=headJSm +	"<meta content='width=device-width, initial-scale=1.0' name='viewport'>";
headJSm=headJSm +	"<meta content='IE=edge' http-equiv='X-UA-Compatible'>";
headJSm=headJSm +	"<link href='docstyle.css' rel='stylesheet' type='text/css'>";
headJSm=headJSm +	"<link href='../helpfiles/FSDA/includesFS/bootstrap.min.css' rel='stylesheet' type='text/css'>";
headJSm=headJSm +	"<meta content='text/javascript' http-equiv='Content-Script-Type'>";
headJSm=headJSm +	"<meta content='cat' itemprop='pagetype' name='toctype'>";
headJSm=headJSm +	"<meta content='cat' itemprop='infotype' name='infotype' />";
headJSm=headJSm +	"<meta content='Flexible Statistics and Data Analysis Toolbox  provides functions and apps to describe, analyze, and model data using robust statistics' itemprop='description' name='description' />";
headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/jquery-latest.js' type='text/javascript'></script>";
headJSm=headJSm +	"<link href='../helpfiles/FSDA/includesFS/site6.css?201601120052' rel='stylesheet' type='text/css'>";
headJSm=headJSm +	"<link href='../helpfiles/FSDA/includesFS/site6_lg.css?201601120052' media='screen and (min-width: 1200px)' rel='stylesheet'>";
headJSm=headJSm +	"<link href='../helpfiles/FSDA/includesFS/site6_md.css?201601120052' media='screen and (min-width: 992px) and (max-width: 1199px)' rel='stylesheet'>";
headJSm=headJSm +	"<link href='../helpfiles/FSDA/includesFS/site6_sm+xs.css?201601120052' media='screen and (max-width: 991px)' rel='stylesheet'>";
headJSm=headJSm +	"<link href='../helpfiles/FSDA/includesFS/site6_sm.css?201601120052' media='screen and (min-width: 768px) and (max-width: 991px)' rel='stylesheet'>";
headJSm=headJSm +	"<link href='../helpfiles/FSDA/includesFS/site6_xs.css?201601120052' media='screen and (max-width: 767px)' rel='stylesheet'>";
headJSm=headJSm +	"<link href='../helpfiles/FSDA/includesFS/site6_offcanvas.css?201601120052' rel='stylesheet' type='text/css'>";
headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/l10n.js'></script>";
headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/SHAREDdocscripts.js'></script>";
headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/PRODUCTdocscripts.js'></script>";
headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/mw.imageanimation.js'></script>";
headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/jquery.highlight.js'></script>";
headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/underscore-min.js'></script>";

headJSm=headJSm + "<script xmlns='http://www.w3.org/1999/xhtml' src='../helpfiles/includes/shared/scripts/F1help.js'></script>";
headJSm=headJSm + "<script xmlns='http://www.w3.org/1999/xhtml' src='../helpfiles/includes/product/scripts/suggest.js'></script>";
headJSm=headJSm + "<script xmlns='http://www.w3.org/1999/xhtml' src='../helpfiles/includes/shared/scripts/helpservices.js'></script>";

headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/bootstrap.min.js' type='text/javascript'></script>";
headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/global.js'></script>";
headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/bottom.js' type='text/javascript'></script>";
headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/lbarm.js' type='text/javascript'></script>";
headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/lbarSimple.js' type='text/javascript'></script>";
headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/enginem.js' type='text/javascript'></script>";
headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/divsbefore.js' type='text/javascript'></script>";
headJSm=headJSm +	"<script src='../helpfiles/FSDA/includesFS/divsafter.js' type='text/javascript'></script>";
headJSm=headJSm +	"<link href='../helpfiles/FSDA/includesFS/doc_center.css' rel='stylesheet' type='text/css'>";
headJSm=headJSm +	"<link href='../helpfiles/FSDA/includesFS/doc_center_installed.css' rel='stylesheet' type='text/css'>";
headJSm=headJSm +	"<link href='../helpfiles/FSDA/includesFS/doc_center_print.css' media='print' rel='stylesheet' type='text/css'>";
headJSm=headJSm +	"<script type='text/x-mathjax-config'>";
headJSm=headJSm +	"MathJax.Hub.Config({";
headJSm=headJSm +	"extensions: ['tex2jax.js'],";
headJSm=headJSm +	"jax: ['input/TeX','output/HTML-CSS'],";
headJSm=headJSm +	"menuSettings: {zoom: 'Double-Click', zscale: '300'},";
headJSm=headJSm +	"tex2jax: {inlineMath: [['$','$'],['\\((','\\))']]},";
headJSm=headJSm +	"MathMenu: {showRenderer: false},";
headJSm=headJSm +	"'HTML-CSS': {";
headJSm=headJSm +	"availableFonts: ['TeX'],";
headJSm=headJSm +	"preferredFont: 'TeX',";
headJSm=headJSm +	"imageFont: null";
headJSm=headJSm +	"}";
headJSm=headJSm +	"});";
headJSm=headJSm +	"</script>";
headJSm=headJSm +	"<script type='text/javascript' src='../helpfiles/FSDA/includesFS/Mathjax/MathJax.js'></script>";
headJSm=headJSm +	"</head>";

