lbarSimple="<div id='sidebar' class='sidebar-offcanvas' role='navigation'>";
lbarSimple=lbarSimple +	"<nav class='offcanvas_nav' role='navigation'>";
lbarSimple=lbarSimple +	"<ul class='nav_breadcrumb' xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbarSimple=lbarSimple +	"<li itemprop='breadcrumb' itemscope='' itemtype='http://www.data-vocabulary.org/Breadcrumb'>";
lbarSimple=lbarSimple +	"				<a href='../documentation-center.html' itemprop='url'>";
lbarSimple=lbarSimple +	"				<span itemprop='title'>All Products</span></a></li>";
lbarSimple=lbarSimple +	"				<li class='product'><a href='index.html'>Flexible Statistics and ";
lbarSimple=lbarSimple +	"				Data Analysis Toolbox</a>";
lbarSimple=lbarSimple +	"				<div class='dropdown'>";
lbarSimple=lbarSimple +	"					<span id='dropdownMenu1' class='icon-arrow-down icon_16' data-toggle='dropdown'>";
lbarSimple=lbarSimple +	"					</span>";
lbarSimple=lbarSimple +	"					<ul aria-labelledby='dropdownMenu1' class='dropdown-menu dropdown-menu-right' role='menu'>";
lbarSimple=lbarSimple +	"						<li role='presentation'>";
lbarSimple=lbarSimple +	"						<a href='examples.html?s_cid=doc_flyout' role='menuitem' tabindex='-1'>";
lbarSimple=lbarSimple +	"						Examples</a></li>";
lbarSimple=lbarSimple +	"						<li role='presentation'>";
lbarSimple=lbarSimple +	"						<a href='function-cate.html?s_cid=doc_flyout' role='menuitem' tabindex='-1'>";
lbarSimple=lbarSimple +	"						Functions and Other Reference</a></li>";
lbarSimple=lbarSimple +	"						<li role='presentation'>";
lbarSimple=lbarSimple +	"						<a href='release_notes.html?s_cid=doc_flyout' role='menuitem' tabindex='-1'>";
lbarSimple=lbarSimple +	"						Release Notes</a></li>";
lbarSimple=lbarSimple +	"						<li role='presentation'>";
lbarSimple=lbarSimple +	"						<a href='tutorials.html' role='menuitem' tabindex='-1'>";
lbarSimple=lbarSimple +	"						Tutorials</a></li>";
lbarSimple=lbarSimple +	"					</ul>";
lbarSimple=lbarSimple +	"				</div>";
lbarSimple=lbarSimple +	"				</li>";
lbarSimple=lbarSimple +	"			</ul>";
