fcate="<ul class='nav_scrollspy nav' xmlns:atict='http://www.arbortext.com/namespace/atict'>";
fcate=fcate + "<li class='nav_scrollspy_function'><a href='#responsive_offcanvas'>Flexible Statistics and Data Analysis Toolbox</a></li>";
fcate=fcate + "		<li id='SSPY810-article' class='nav_scrollspy_title'>On this page</li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#REG'>Robust regression analysis and transformations</a><ul>";
fcate=fcate + "			<li><a class='intrnllnk' href='#REG-Regression'>Robust regression</a></li>";
fcate=fcate + "			<li><a class='intrnllnk' href='#REG-Transformations'>Robust transformations</a></li>";
fcate=fcate + "			<li><a class='intrnllnk' href='#REG-ModelSelection'>Robust model selection</a></li>";
fcate=fcate + "			<li><a class='intrnllnk' href='#REG-Bayes'>Robust Bayesian regression</a></li>";
fcate=fcate + "			<li><a class='intrnllnk' href='#REG-Hetero'>Robust heteroskedastic regression</a></li>";
fcate=fcate + "		</ul>";
fcate=fcate + "		</li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#MULT'>Robust multivariate analysis and transformations</a><ul>";
fcate=fcate + "			<li><a class='intrnllnk' href='#MULT-Multivariate'>Robust multivariate Analysis</a></li>";
fcate=fcate + "			<li><a class='intrnllnk' href='#MULT-Transformations'>Robust transformations</a></li>";
fcate=fcate + "		</ul>";
fcate=fcate + "		</li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#CLUS'>Robust clustering</a><ul>";
fcate=fcate + "			<li><a class='intrnllnk' href='#CLUS-MixSim'>MixSim</a></li>";
fcate=fcate + "			<li><a class='intrnllnk' href='#CLUS-RobClaREG'>Robust clustering in regression</a></li>";
fcate=fcate + "			<li><a class='intrnllnk' href='#CLUS-RobClaMULT'>Robust clustering in multivariate analysis</a></li>";
fcate=fcate + "		</ul>";
fcate=fcate + "		</li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#VIS'>Dynamic visualization</a><ul>";
fcate=fcate + "			<li><a class='intrnllnk' href='#VIS-Reg'>Dynamic visualization in regression</a></li>";
fcate=fcate + "			<li><a class='intrnllnk' href='#VIS-Mult'>Dynamic visualization in multivariate analysis</a></li>";
fcate=fcate + "			<li><a class='intrnllnk' href='#VIS-Clu'>Dynamic visualization in clustering</a></li>";
fcate=fcate + "		</ul>";
fcate=fcate + "		</li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#GUI'>Guis</a>";
fcate=fcate + "		</li>";
fcate=fcate + "		<li><a class='intrnllnk' href='#UTI'>Utilities</a><ul>";
fcate=fcate + "			<li><a class='intrnllnk' href='#UTISTAT'>Statistical utilities</a></li>";
fcate=fcate + "			<li><a class='intrnllnk' href='#UTIGEN'>General utilities</a></li>";
fcate=fcate + "			<li><a class='intrnllnk' href='#UTICOMB'>Combinatorial routines</a></li>";
fcate=fcate + "			<li><a class='intrnllnk' href='#UTIHELP'>Automatic creation of HTML help</a></li>";
fcate=fcate + "		</ul>";
fcate=fcate + "		</li>";
fcate=fcate + "	</ul>";