engine="<div class='sticky_header_container includes_subnav'>";
engine=engine + "<div class='section_header level_3'>";
engine=engine + "<div class='container-fluid'>";
engine=engine + "			<div id='mobile_search_row' class='row'>";
engine=engine + "				<div id='mobile_search' class='col-xs-12 col-sm-6 col-sm-push-6 col-md-5 col-md-push-7'>";
engine=engine + "					<div class='search_nested_content_container'>";
engine=engine + "<gcse:search></gcse:search>";
engine=engine + "					</div>";
engine=engine + "					<button aria-controls='mobile_search' aria-expanded='false' class='btn icon-remove btn_search pull-right icon_32 visible-xs' data-toggle='collapse' href='#mobile_search'>";
engine=engine + "					</button></div>";
engine=engine + "				<div id='section_header_title' class='col-sm-6 col-sm-pull-6 col-md-7 col-md-pull-5'>";
engine=engine + "					<div class='section_header_content'>";
engine=engine + "						<div class='section_header_title'>";
engine=engine + "							<h1><a href='../documentation-center.html'>Documentation</a></h1>";
engine=engine + "						</div>";
engine=engine + "					</div>";
engine=engine + "				</div>";
engine=engine + "				<div id='search_actuator' class='visible-xs'>";
engine=engine + "					<button aria-controls='mobile_search' aria-expanded='false' class='btn icon-search btn_search pull-right icon_16' data-toggle='collapse' href='#mobile_search'>";
engine=engine + "					</button></div>";
engine=engine + "			</div>";
engine=engine + "			<!--END.CLASS row--></div>";
engine=engine + "		<!--END.CLASS container-fluid--></div>";
engine=engine + "	<!--END.CLASS section_header level_3-->";
engine=engine + "	<div class='horizontal_nav'>";
engine=engine + "		<div class='horizontal_nav_container'>";
engine=engine + "			<div id='nav_toggle' class='offcanvas_actuator' data-target='#sidebar' data-toggle='offcanvas'>";
engine=engine + "				<button class='btn' type='button'><span class='sr-only'>Toggle navigation</span><span class='icon-menu icon_24'></span>";
engine=engine + "				</button><span class='offcanvas_actuator_label'></span>";
engine=engine + "				<span class='offcanvas_actuator_close'></span></div>";
engine=engine + "			<div class='offcanvas_horizontal_nav'>";
engine=engine + "				<div class='container-fluid'>";
engine=engine + "					<div class='row'>";
engine=engine + "						<div class='col-md-12 hidden-xs hidden-sm'>";
engine=engine + "						</div>";
engine=engine + "					</div>";
engine=engine + "				</div>";
engine=engine + "			</div>";
engine=engine + "		</div>";
engine=engine + "	</div>";
engine=engine + "</div>";