lbarm="<div id='sidebar' class='sidebar-offcanvas' role='navigation'>";
lbarm=lbarm+"		<nav class='offcanvas_nav' role='navigation'>";
lbarm=lbarm+"			<ul class='nav_breadcrumb' xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbarm=lbarm+"				<li itemprop='breadcrumb' itemscope='' itemtype='http://www.data-vocabulary.org/Breadcrumb'>";
lbarm=lbarm+"				<a href='../documentation-center.html' itemprop='url'>";
lbarm=lbarm+"				<span itemprop='title'>All Products</span></a></li>";
lbarm=lbarm+"			</ul>";
lbarm=lbarm+"			<ul class='nav_disambiguation' xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbarm=lbarm+"				<li class='product'><a href='index.html'>Flexible Statistics and ";
lbarm=lbarm+"				Data Analysis (FSDA)</a>";
lbarm=lbarm+"				<div class='dropdown'>";
lbarm=lbarm+"					<span id='dropdownMenu1' class='icon-arrow-down icon_16' data-toggle='dropdown'>";
lbarm=lbarm+"					</span>";
lbarm=lbarm+"					<ul aria-labelledby='dropdownMenu1' class='dropdown-menu dropdown-menu-right' role='menu'>";
lbarm=lbarm+"						<li role='presentation'>";
lbarm=lbarm+"						<a href='../helpfiles/FSDA/examples.html' role='menuitem' tabindex='-1'>Examples</a></li>";
lbarm=lbarm+"						<li role='presentation'>";
lbarm=lbarm+"						<a href='../helpfiles/FSDA/function-alpha.html' role='menuitem' tabindex='-1'>";
lbarm=lbarm+"						Functions and Other Reference</a></li>";
lbarm=lbarm+"						<li role='presentation'>";
lbarm=lbarm+"						<a href='../helpfiles/FSDA/release_notes.html?s_cid=doc_flyout' role='menuitem' tabindex='-1'>";
lbarm=lbarm+"						Release Notes</a></li>";
lbarm=lbarm+"						<li role='presentation'>";
lbarm=lbarm+"						<a href='../helpfiles/FSDA/tutorials.html' role='menuitem' tabindex='-1'>Tutorials</a></li>";
lbarm=lbarm+"					</ul>";
lbarm=lbarm+"				</div>";
lbarm=lbarm+"				</li>";
lbarm=lbarm+"			</ul>";
lbarm=lbarm+"            <!--END of Include lbarmsimple.js-->	";
lbarm=lbarm+"            <!-- this is left out of barsimple";
lbarm=lbarm+"			<ul class='nav_disambiguation' xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbarm=lbarm+"				<li><a href='../helpfiles/FSDA/index.html'>Flexible Statistics and Data Analysis Toolbox</a>";
lbarm=lbarm+"				</li>";
lbarm=lbarm+"				<li><a href='../helpfiles/FSDA/function-cate.html' itemprop='url'>Functions</a></li>";
lbarm=lbarm+"			</ul>";
lbarm=lbarm+"        -->";
lbarm=lbarm+"			<!-- -->";
lbarm=lbarm+"			<ul class='nav_scrollspy nav' xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbarm=lbarm+"				<li xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbarm=lbarm +	"				<a class='corrected_url' href='../helpfiles/FSDA/getting-started.html'>Getting ";
lbarm=lbarm +	"				Started with Flexible Statistics and Data Analysis Toolbox </a>";
lbarm=lbarm +	"				</li>";
lbarm=lbarm +	"				<li xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbarm=lbarm +	"				<a class='corrected_url' href='../helpfiles/FSDA/function-cate.html'>";
lbarm=lbarm +	"				Functions</a></li>";
lbarm=lbarm +	"				<li xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbarm=lbarm +	"				<a class='corrected_url' href='../helpfiles/FSDA/datasets.html'>Datasets</a>";
lbarm=lbarm +	"				</li>";
lbarm=lbarm +	"				<li xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbarm=lbarm +	"				<a class='corrected_url' href='../helpfiles/FSDA/bibliography.html'>Bibliography</a></li>";
lbarm=lbarm +	"				<li xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbarm=lbarm +	"				<a class='corrected_url' href='../helpfiles/FSDA/release_notes.html'>Release ";
lbarm=lbarm +	"				notes </a></li>";
lbarm=lbarm +	"				<li xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbarm=lbarm +	"				<a class='corrected_url' href='../helpfiles/FSDA/examples.html'>Examples </a></li>";
lbarm=lbarm +	"				<li xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbarm=lbarm +	"				<a class='corrected_url' href='../helpfiles/FSDA/tutorials.html'>Tutorials </a></li>";
lbarm=lbarm+"			</ul>";
lbarm=lbarm+"		</nav>";
lbarm=lbarm+"		<script src='../helpfiles/includes/product/scripts/offcanvas.js'></script>";
lbarm=lbarm+"    </div>";


