lbar="<div id='sidebar' class='sidebar-offcanvas' role='navigation'>";
lbar=lbar+"		<nav class='offcanvas_nav' role='navigation'>";
lbar=lbar+"			<ul class='nav_breadcrumb' xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbar=lbar+"				<li itemprop='breadcrumb' itemscope='' itemtype='http://www.data-vocabulary.org/Breadcrumb'>";
lbar=lbar+"				<a href='../documentation-center.html' itemprop='url'>";
lbar=lbar+"				<span itemprop='title'>All Products</span></a></li>";
lbar=lbar+"			</ul>";
lbar=lbar+"			<ul class='nav_disambiguation' xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbar=lbar+"				<li class='product'><a href='index.html'>Flexible Statistics and ";
lbar=lbar+"				Data Analysis (FSDA)</a>";
lbar=lbar+"				<div class='dropdown'>";
lbar=lbar+"					<span id='dropdownMenu1' class='icon-arrow-down icon_16' data-toggle='dropdown'>";
lbar=lbar+"					</span>";
lbar=lbar+"					<ul aria-labelledby='dropdownMenu1' class='dropdown-menu dropdown-menu-right' role='menu'>";
lbar=lbar+"						<li role='presentation'>";
lbar=lbar+"						<a href='examples.html' role='menuitem' tabindex='-1'>Examples</a></li>";
lbar=lbar+"						<li role='presentation'>";
lbar=lbar+"						<a href='function-alpha.html' role='menuitem' tabindex='-1'>";
lbar=lbar+"						Functions and Other Reference</a></li>";
lbar=lbar+"						<li role='presentation'>";
lbar=lbar+"						<a href='release_notes.html?s_cid=doc_flyout' role='menuitem' tabindex='-1'>";
lbar=lbar+"						Release Notes</a></li>";
lbar=lbar+"						<li role='presentation'>";
lbar=lbar+"						<a href='tutorials.html' role='menuitem' tabindex='-1'>Tutorials</a></li>";
lbar=lbar+"					</ul>";
lbar=lbar+"				</div>";
lbar=lbar+"				</li>";
lbar=lbar+"			</ul>";
lbar=lbar+"            <!--END of Include lbarsimple.js-->	";
lbar=lbar+"            <!-- this is left out of barsimple";
lbar=lbar+"			<ul class='nav_disambiguation' xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbar=lbar+"				<li><a href='index.html'>Flexible Statistics and Data Analysis Toolbox</a>";
lbar=lbar+"				</li>";
lbar=lbar+"				<li><a href='function-cate.html' itemprop='url'>Functions</a></li>";
lbar=lbar+"			</ul>";
lbar=lbar+"        -->";
lbar=lbar+"			<!-- -->";
lbar=lbar+"			<ul class='nav_scrollspy nav' xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbar=lbar+"				<li xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbar=lbar +	"				<a class='corrected_url' href='getting-started.html'>Getting ";
lbar=lbar +	"				Started with Flexible Statistics and Data Analysis Toolbox </a>";
lbar=lbar +	"				</li>";
lbar=lbar +	"				<li xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbar=lbar +	"				<a class='corrected_url' href='function-cate.html'>";
lbar=lbar +	"				Functions</a></li>";
lbar=lbar +	"				<li xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbar=lbar +	"				<a class='corrected_url' href='datasets.html'>Datasets</a>";
lbar=lbar +	"				</li>";
lbar=lbar +	"				<li xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbar=lbar +	"				<a class='corrected_url' href='bibliography.html'>Bibliography</a></li>";
lbar=lbar +	"				<li xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbar=lbar +	"				<a class='corrected_url' href='release_notes.html'>Release ";
lbar=lbar +	"				notes </a></li>";
lbar=lbar +	"				<li xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbar=lbar +	"				<a class='corrected_url' href='examples.html'>Examples </a></li>";
lbar=lbar +	"				<li xmlns:atict='http://www.arbortext.com/namespace/atict'>";
lbar=lbar +	"				<a class='corrected_url' href='tutorials.html'>Tutorials </a></li>";
lbar=lbar+"			</ul>";
lbar=lbar+"		</nav>";
lbar=lbar+"		<script src='../includes/product/scripts/offcanvas.js'></script>";
lbar=lbar+"    </div>";


