---
name: "build-docker-container"

on:
  workflow_dispatch:
    inputs:
      matlab-release:
        required: false
        type: string
        default: latest
      fsda-release:
        required: true
        type: string

jobs:
       
  build-docker-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on your repository
        uses: actions/checkout@v3
      
      - name: Build Docker Container
        uses: josmartin/FSDA/.github/workflows/reusable-build-docker-container.yml@master
        with:
          matlab-release: ${{ github.event.inputs.matlab-release }}
          fsda-release: ${{ github.event.inputs.fsda-release }}
