---
name: "build-docker-container"

on:
  workflow_dispatch:
    inputs:
      matlab-release:
        required: false
        type: string
        default: latest
      fsda-release:
        required: true
        type: string

jobs:
  build-docker-container:
    uses: ./.github/workflows/reusable-build-docker-container.yml
    with:
      matlab-release: ${{ github.event.inputs.matlab-release }}
      fsda-release: ${{ github.event.inputs.fsda-release }}
    secrets: inherit
