---
name: "build-docker-container"

on:
  workflow_dispatch:
    inputs:
      matlab-release:
        required: false
        type: string
        default: latest
      fsda-release:
        required: true
        type: string

jobs:

  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on your repository
        uses: actions/checkout@v3

  build-docker-container:
    needs: checkout-repo
    uses: ./.github/workflows/reusable-build-docker-container.yml
    with:
      matlab-release: ${{ github.event.inputs.matlab-release }}
      fsda-release: ${{ github.event.inputs.fsda-release }}
    secrets: inherit
