# This is a workflow for building the MLTBX artifact and release it on GitHub

name: Build MLTBX tag triggered

# Start the workflow when a tag is created.
on:
  push:
    tags:
      - 'v*'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "MLTBXBuild"
  MLTBXBuildTag:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - name: checkout the repo
        uses: actions/checkout@v3
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      
      - name: Create MLTBX
        uses: matlab-actions/run-command@v1
        continue-on-error: true
        if: always()
        with:
          # command: matlab.addons.toolbox.packageToolbox("fsdaToolboxPackaging.prj", "release/fsda.mltbx")
          command: run utilities_help/createFSDAToolboxActions
      
      # Save the MLTBX.
      - name: Save MLTBX
        uses: actions/upload-artifact@v3
        with:
          name: FSDA build MLTBX
          path: release/fsda.mltbx
          
      # Create the release
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          draft: false        
          artifacts: "release/fsda.mltbx"
          generateReleaseNotes: true
