# Publish GitHub release assets (FSDA.mltbx file to be compatible with
# MathWorks FileExchange new 'link your [repo] to GitHub' feature.)
name: Publish FSDA.mltbx to GitHub release assets 

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '*' # Push events to matching *, i.e. v1.0 or 18.6.1

#  release:
#    types:
#      - published

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    
    outputs: 
      fsda-release: ${{ steps.extract_tag.outputs.tag }}

    steps:
      - name: Checkout on your repository
        uses: actions/checkout@v1
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # Forks of this repo can have failed to build the MLTBX output so conditionally check for its 
      # existence and let other steps know about this.
      - name: Check MLTBX file exists
        id: mltbx-check
        shell: bash
        run: |
          echo "::set-output name=exist::$(test -f ./bin/FSDA.mltbx && echo true || echo false)"

      - name: Upload Release Asset
        if: ${{ steps.mltbx-check.outputs.exist == 'true' }}
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          #GITHUB_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #upload_url: github.event.release.upload_url
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/FSDA.mltbx
          asset_name: FSDA.mltbx
          asset_content_type: application/gzip

      - name: Extract tag from this release
        id: extract_tag
        shell: bash
        run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
      
  build-docker-container:
    needs: archive-build-artifacts
    uses: ./.github/workflows/reusable-build-docker-container.yml
    with:
      matlab-release: latest
      fsda-release: ${{ needs.archive-build-artifacts.outputs.fsda-release }}
    secrets: inherit
